channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.16.3
  - matplotlib=3.0.3
  - pillow=6.2.1
  - earthengine-api=0.1.236
  - mapclassify=2.4.2
  - gdal=2.4
  - pandas=1.0
  - geopandas=0.4.1
  - pytz=2020.1
  - scikit-image=0.15.0
  - scikit-learn=0.20.3
  - shapely=1.6.4
  - scipy=1.2.1
  - astropy=3.2.1
  - notebook
  - pyqt
  - basemap
  - basemap-data-hires
